// Generated by CoffeeScript 1.6.2
(function() {
  var CelestialBody, HALF_PI, TWO_PI, G, Sun, Moho, Eve, Gilly, Kerbin, Mun, Minmus, Duna, Ike, Edna, Dak, Dres, Jool, Laythe, Vall, Tylo, Bop, Pol, Lindor, Krel, Aden, Huygen, Riga, Talos, Eeloo, Celes, Tam, Hamek, Nara, Amos, Enon, Prax, Grannus, Taranis, Toutatis, Nodens, Belisama, Sucellus, Caireen, Sirona, Airmed, Brovo, Damona, Epona, Rosmerta, RAB-58E, Cernunnos;

  G = 6.674e-11;

  TWO_PI = 2 * Math.PI;

  HALF_PI = 0.5 * Math.PI;

  (typeof exports !== "undefined" && exports !== null ? exports : this).CelestialBody = CelestialBody = (function() {
    function CelestialBody(mass, radius, siderealRotation, orbit, atmPressure, atmScaleHeight) {
      this.mass = mass;
      this.radius = radius;
      this.siderealRotation = siderealRotation;
      this.orbit = orbit;
      this.atmPressure = atmPressure != null ? atmPressure : 0;
      this.atmScaleHeight = atmScaleHeight != null ? atmScaleHeight : 0;
      this.gravitationalParameter = G * this.mass;
      if (this.orbit != null) {
        this.sphereOfInfluence = this.orbit.semiMajorAxis * Math.pow(this.mass / this.orbit.referenceBody.mass, 0.4);
      }
      this.atmRadius = -Math.log(1e-6) * this.atmScaleHeight + this.radius;
    }

    CelestialBody.prototype.circularOrbitVelocity = function(altitude) {
      return Math.sqrt(this.gravitationalParameter / (altitude + this.radius));
    };

    CelestialBody.prototype.siderealTimeAt = function(longitude, time) {
      var result;

      result = ((time / this.siderealRotation) * TWO_PI + HALF_PI + longitude) % TWO_PI;
      if (result < 0) {
        return result + TWO_PI;
      } else {
        return result;
      }
    };

    CelestialBody.prototype.name = function() {
      var k, v;

      for (k in CelestialBody) {
        v = CelestialBody[k];
        if (v === this) {
          return k;
        }
      }
    };

    CelestialBody.prototype.children = function() {
      var k, result, v, _ref;

      result = {};
      for (k in CelestialBody) {
        v = CelestialBody[k];
        if ((v != null ? (_ref = v.orbit) != null ? _ref.referenceBody : void 0 : void 0) === this) {
          result[k] = v;
        }
      }
      return result;
    };

    return CelestialBody;

  })();

  CelestialBody.fromJSON = function(json) {
    var orbit;

    if (json.orbit != null) {
      orbit = Orbit.fromJSON(json.orbit);
    }
    return new CelestialBody(json.mass, json.radius, json.siderealRotation, orbit, json.atmPressure);
  };

  CelestialBody.Sun = Sun = new CelestialBody(1.25719e29, 175750000, 1080000, null);
  CelestialBody.Moho = Moho = new CelestialBody(1.80034e22, 650000, 2530758.15664, new Orbit(Sun, 14522400000, 0.2, 7, 70, 15, 0));
  CelestialBody.Eve = Eve = new CelestialBody(8.645e23, 2050000, 81000, new Orbit(Sun, 27131000000, 0.01, 2.1, 15, 45, 5.7));
  CelestialBody.Gilly = Gilly = new CelestialBody(991820000000000000, 30000, 670318.534840231, new Orbit(Eve, 86920000, 0.55, 12, 80, 10, 0));
  CelestialBody.Kerbin = Kerbin = new CelestialBody(3.76157e23, 1600000, 43200, new Orbit(Sun, 37525647898.4324, 0.02, 0, 0, 0, 0));
  CelestialBody.Mun = Mun = new CelestialBody(3.40892e21, 800000, 50400, new Orbit(Kerbin, 57189100000, 0.051, 0.06, 135.5, 345, 0.9));
  CelestialBody.Minmus = Minmus = new CelestialBody(1.88079e20, 160000, 32400, new Orbit(Kerbin, 146970000, 0.03, 6, 75, 315, 30));
  CelestialBody.Duna = Duna = new CelestialBody(3.19734e22, 800000, 50400, new Orbit(Sun, 57189100000, 0.051, 0.06, 135.5, 345, 0.9));
  CelestialBody.Ike = Ike = new CelestialBody(3.88794e20, 210000, 955507.445592476, new Orbit(Duna, 36680000, 0.03, 0.2, 90, 345, 180));
  CelestialBody.Edna = Edna = new CelestialBody(7.94632e20, 260000, 10800, new Orbit(Sun, 94080000000, 0.07, 3, 30, 310, 0));
  CelestialBody.Dak = Dak = new CelestialBody(470196000000000000, 20000, 284235.787218621, new Orbit(Edna, 4770000, 0.01, 10, 120, 90, 0));
  CelestialBody.Dres = Dres = new CelestialBody(2.28515e21, 360000, 16200, new Orbit(Sun, 112687000000, 0.145, 5, 280, 90, 3.9));
  CelestialBody.Jool = Jool = new CelestialBody(2.99515e25, 14000000, 19800, new Orbit(Sun, 189765000000, 0.05, 1.304, 52, 30, 0.6));
  CelestialBody.Laythe = Laythe = new CelestialBody(1.0312e23, 1100000, 115299.753436233, new Orbit(Jool, 87640000, 0.01, 0.2, 120, 120, 180));
  CelestialBody.Vall = Vall = new CelestialBody(8.00068e21, 550000, 285030.00096071, new Orbit(Jool, 160230000, 0.03, 0.3, 90, 270, 180));
  CelestialBody.Tylo = Tylo = new CelestialBody(3.80859e22, 900000, 704636.407486379, new Orbit(Jool, 292950000, 0.01, 0.1, 150, 285, 270));
  CelestialBody.Bop = Bop = new CelestialBody(2.6522e20, 190000, 1978081.28781907, new Orbit(Jool, 582970000, 0.235, 15, 10, 25, 270));
  CelestialBody.Pol = Pol = new CelestialBody(74496700000000000000, 130000, 18000, new Orbit(Jool, 739460000, 0.17085, 4.25, 2, 15, 1.8));
  CelestialBody.Lindor = Lindor = new CelestialBody(8.83969e24, 8000000, 25200, new Orbit(Sun, 359571000000, 0.03, 1.7, 80, 75, 3.3));
  CelestialBody.Krel = Krel = new CelestialBody(99182000000000000000, 150000, 116041.154455211, new Orbit(Lindor, 58600000, 0.02, 1.5, 60, 180, 0));
  CelestialBody.Aden = Aden = new CelestialBody(9.25699e20, 300000, 286875.24899704, new Orbit(Lindor, 107140000, 0.01, 0.25, 120, 30, 270));
  CelestialBody.Huygen = Huygen = new CelestialBody(9.89396e21, 670000, 664152.061283006, new Orbit(Lindor, 187500000, 0.025, 0.75, 150, 60, 90));
  CelestialBody.Riga = Riga = new CelestialBody(1.48773e22, 750000, 1407680.09452737, new Orbit(Lindor, 309380000, 0.03, 0.5, 90, 105, 180));
  CelestialBody.Talos = Talos = new CelestialBody(4.04075e21, 500000, 3573035.48442024, new Orbit(Lindor, 575680000, 0.04, 1, 180, 285, 90));
  CelestialBody.Eeloo = Eeloo = new CelestialBody(7.93456e21, 600000, 14400, new Orbit(Sun, 471171300000, 0.26, 6.15, 50, 260, 3.54));
  CelestialBody.Celes = Celes = new CelestialBody(2.35098e20, 200000, 1548329.29408971, new Orbit(Eeloo, 31800000, 0.05, 10, 100, 270, 0));
  CelestialBody.Tam = Tam = new CelestialBody(51427700000000000, 10000, 4490316.38364019, new Orbit(Eeloo, 64670000, 0.025, 9.5, 105, 210, 180));
  CelestialBody.Hamek = Hamek = new CelestialBody(2.97546e21, 450000, 14400, new Orbit(Sun, 527129000000, 0.1, 4, 165, 175, 4.7));
  CelestialBody.Nara = Nara = new CelestialBody(1.9043e24, 3600000, 43200, new Orbit(Sun, 1712000000000, 0.35, 20, 90, 150, 2.5));
  CelestialBody.Amos = Amos = new CelestialBody(9.02777e20, 320000, 232809.997387739, new Orbit(Nara, 55880000, 0.01, 0.5, 180, 345, 180));
  CelestialBody.Enon = Enon = new CelestialBody(1.07998e22, 700000, 788078.420847453, new Orbit(Nara, 125980000, 0.015, 0.2, 270, 0, 180));
  CelestialBody.Prax = Prax = new CelestialBody(35558600000000000000, 110000, 21600, new Orbit(Nara, 751900000, 0.4, 17, 95, 100, 0));
  CelestialBody.Grannus = Grannus = new CelestialBody(5.96840268332872e28, 75425000, 2592000, new Orbit(Sun, 5000000000000, 0.1, 7, 195, 20, -0.426));
  CelestialBody.Taranis = Taranis = new CelestialBody(7.34681783856352e21, 500000, 52170.5170334447, new Orbit(Grannus, 650000000, 0.02, 9, 140, 345, 3.141592654));
  CelestialBody.Toutatis = Toutatis = new CelestialBody(5.06241666688517e22, 875000, 922118.734223791, new Orbit(Grannus, 4410500000, 0.015, 10.5, 160, 300, 0));
  CelestialBody.Nodens = Nodens = new CelestialBody(4.94991851873217e23, 1750000, 243000, new Orbit(Grannus, 6200835067.84755, 0.02, 10, 155, 30, 0));
  CelestialBody.Sucellus = Sucellus = new CelestialBody(2.89280952393439e21, 375000, 28800, new Orbit(Grannus, 14742500000, 0.09, 7, 170, 45, 4));
  CelestialBody.Sirona = Sirona = new CelestialBody(8.26517006838396e24, 7500000, 57600, new Orbit(Grannus, 29750000000, 0.04, 10, 150, 0, 3.141592654));
  CelestialBody.Epona = Epona = new CelestialBody(1.37752834473066e23, 1250000, 36000, new Orbit(Grannus, 58750000000, 0.06, 11, 145, 90, 0));
  CelestialBody.Cernunnos = Cernunnos = new CelestialBody(9.25699047659003e20, 300000, 21600, new Orbit(Grannus, 93250000000, 0.175, 4, 120, 180, 0.5));

}).call(this);
